added functionality to filter results by keys in _list.py
awslabs/aws-data-wrangler pull request #416
Opened 2020-10-06 14:38 UTC by pietropra

*Description of changes:* Added the ability to filter out results by specifying a keyword for keys/prefix in wr.s3.list_objects()

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-06 16:01 UTC, igorborgest requested changes
Thanks @pietropra ! It's a cool feature.

I've leaved some comments and also missed some test to cover it.

2020-10-07 09:06 UTC, pietropra commented on awswrangler/s3/_list.py
> +        paths = [p for p in paths if not any([search(key, p) for key in _excluded_keys])]
Thanks Igor, good suggestions. I will work on this further and re-submit

2020-10-07 17:00 UTC, pietropra commented on awswrangler/s3/_list.py
> +        paths = [p for p in paths if not any([search(key, p) for key in _excluded_keys])]
HI, I have pushed a new commit

I changed parse_path to return a list of key parts, and a check in list_objects to return filtered paths if any key part matches the excluded keys in the excluded_keys argument.

Let me know if this is any better?

2020-10-14 22:13 UTC, pietropra commented
@igorborgest 

Now `list_objects `works by breaking down the key after bucket into parts and, if `excluded _keys` is not `None`, it filters out the objects that have a key from the excluded keys (either a String or List of Strings).

This is an example of `parse_path` behaves when `excluded_keys `is not `None`:
```
paths = [
    's3://bucket/prefix/archive',
    's3://bucket/prefix/my-foo-archive',
]

excluded_keys = [
    'archive',
    'logs',
]

paths_to_keep = []
for p in paths:
    _, prefix, keyparts = parse_path(p, multipart=True)
    if not any(key in keyparts for key in excluded_keys):
        paths_to_keep.append(p)

paths_to_keep
```
`paths_to_keep` becomes `['s3://bucket/prefix/my-foo-archive']`

Mypy is throwing some errors for how the tuple resulting from `parse_path `is unpacked in `list_objects`: the way is implemented is checking if a `multipart `argument is `True `(default `False`). 
Maybe another way to go about it it might be to separate the functions e.g. creating something like `list_and_filter_objects`, but I tried to keep the change minimal, what do you think?

2020-10-14 22:35 UTC, igorborgest commented
Yeah, unfortunately mypy will only consider this two different possibilities of return types safe if you check it before unpack for ALL usages. But event tough I don't think this is the best way. A new parse_path function specialized to return all the parts would be better.

But before this change I would like to take a step back and understand better the final goal. The idea is to filter by black listed filenames in the end of the object key OR black listed directories in the middle of the object key?

2020-12-11 10:59 UTC, igorborgest commented
closing by inactivity

2020-12-11 10:59 UTC, closed without merging