WIP: First draft for DynamoDB support
awslabs/aws-data-wrangler pull request #493
Opened 2020-12-28 20:58 UTC by maxispeicher

*Issue #448

*Description of changes:*
Adding new module for writing to DynamoDB tables. The new module supports writing data which is stored in JSON-Files, CSV-Files or DataFrames. All possibilities call `_put_items` in the event which uses the `BatchWriter` from `boto3` for inserting the items to the table.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-28 21:22 UTC, igorborgest reviewed
We are in the right way here! 🚀

2020-12-28 21:32 UTC, dwbelliston commented
Hey, thanks for working on this! Would love to delete my code and get this in the library. 

Here is what I ended up doing in my app to get this functionality, so it looks like you are doing something very similiar.

```python
try:

    with self.Table.batch_writer() as batch:
        for record in records:

            # Get to json dict to be used by dynamodb client
            try:
                record_data = jsonable_encoder(record)
            except Exception as err:
                LOGGER.exception(err)
                raise exceptions.ConvertToJsonFailed()

            if operation == BatchWriteOperations.delete:
                batch.delete_item(
                    Key={"PK": record_data["PK"], "SK": record_data["SK"]}
                )

            else:
                batch.put_item(Item=record_data)

except Exception as err:
    LOGGER.exception(err)
    raise exceptions.BatchWriteRecordsFailed()
```

Could we also add a function to pass in json? Basically have an option to read from json file, which in turn calls the write json, but also expose that internal write json call? In my case, the json is sent to me in an api call, so im not reading it from a file.

Im also doing some work to batch delete from the table, could we support that?

Thanks for the effort here.

2020-12-28 23:30 UTC, maxispeicher commented
`put_items` now also is publicly available. Additionally deleting items is supported :)

2020-12-28 23:44 UTC, dwbelliston commented on awswrangler/dynamodb/_delete.py
> +        List which contains the items that will be inserted.
inserted, or deleted?

2020-12-28 23:45 UTC, dwbelliston commented on awswrangler/dynamodb/_delete.py
> +            writer.delete_item(Key={key: item[key] for key in table_keys})
👏 - awesome - like that this is dynamic instead of my static solution

2020-12-28 23:47 UTC, dwbelliston commented on awswrangler/dynamodb/_write.py
> +def put_items(
thanks for exposing this :)

2020-12-28 23:50 UTC, maxispeicher commented on awswrangler/dynamodb/_delete.py
> +        List which contains the items that will be inserted.
Deleted. Thank you

2020-12-29 17:41 UTC, igorborgest requested changes
LGTM. It is only missing the API reference docs, could you accept the PR that I sent you to update it?

2020-12-29 18:27 UTC, igorborgest approved these changes
Thank you @maxispeicher !

2020-12-30 17:42 UTC, merged